# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "031f6f404f6e29d8a6b56754e91e9cee"
name = "Moast Shopping Widget"
handle = "moast-shopping-widget-1"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "moast-staging.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
